'use server';
/**
 * @fileOverview A flow to detect if an image is AI-generated.
 *
 * - detectAiImage - A function that handles the image analysis.
 * - DetectAiImageInput - The input type for the detectAiImage function.
 * - DetectAiImageOutput - The return type for the detectAiImage function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const DetectAiImageInputSchema = z.object({
  photoDataUri: z
    .string()
    .describe(
      "A photo of a plant, as a data URI that must include a MIME type and use Base64 encoding. Expected format: 'data:<mimetype>;base64,<encoded_data>'."
    ),
});
export type DetectAiImageInput = z.infer<typeof DetectAiImageInputSchema>;

const DetectAiImageOutputSchema = z.object({
  isAiGenerated: z.boolean().describe('Whether or not the image is AI generated.'),
  confidence: z.number().describe('A confidence score between 0 and 1 on the prediction.'),
});
export type DetectAiImageOutput = z.infer<typeof DetectAiImageOutputSchema>;

export async function detectAiImage(input: DetectAiImageInput): Promise<DetectAiImageOutput> {
  return detectAiImageFlow(input);
}

const prompt = ai.definePrompt({
  name: 'detectAiImagePrompt',
  input: {schema: DetectAiImageInputSchema},
  output: {schema: DetectAiImageOutputSchema},
  prompt: `You are an expert in detecting AI-generated images.
You will be given an image and you must determine if it was generated by an AI model.

Respond with whether or not you think the image is AI-generated and a confidence score for your prediction.
If you are very sure it is AI, the confidence score should be close to 1.
If you are very sure it is not AI, the confidence score should be close to 0.

Image: {{media url=photoDataUri}}`,
});

const detectAiImageFlow = ai.defineFlow(
  {
    name: 'detectAiImageFlow',
    inputSchema: DetectAiImageInputSchema,
    outputSchema: DetectAiImageOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
