
'use client';

import { useState } from 'react';
import { Card } from '@/components/ui/card';
import { Bot, RefreshCw } from 'lucide-react';
import { ImageUpload } from '@/components/image-upload';
import { detectAiImage, DetectAiImageOutput } from '@/ai/flows/detect-ai-image-flow';
import { ResultsDisplay } from '@/components/results-display';
import { Button } from '@/components/ui/button';
import { Skeleton } from '@/components/ui/skeleton';

export default function Home() {
  const [analysisResult, setAnalysisResult] = useState<DetectAiImageOutput | null>(null);
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const handleImageUpload = async (file: File) => {
    setIsAnalyzing(true);
    setError(null);
    setAnalysisResult(null);

    const reader = new FileReader();
    reader.readAsDataURL(file);
    reader.onload = async () => {
      try {
        const photoDataUri = reader.result as string;
        const result = await detectAiImage({ photoDataUri });
        setAnalysisResult(result);
      } catch (e) {
        setError('An error occurred during analysis. Please try again.');
        console.error(e);
      } finally {
        setIsAnalyzing(false);
      }
    };
    reader.onerror = () => {
      setError('Failed to read the image file.');
      setIsAnalyzing(false);
    };
  };

  const handleReset = () => {
    setAnalysisResult(null);
    setIsAnalyzing(false);
    setError(null);
  }

  const renderContent = () => {
    if (isAnalyzing) {
      return (
        <Card className="w-full bg-card/80 backdrop-blur-sm border-border/20 shadow-xl shadow-black/10 overflow-hidden rounded-2xl p-6 flex flex-col items-center justify-center text-center">
            <Skeleton className="w-full aspect-video rounded-lg" />
            <Skeleton className="h-10 w-32 mt-4" />
        </Card>
      );
    }

    if (analysisResult) {
      return (
        <div>
          <ResultsDisplay {...analysisResult} />
          <div className="text-center mt-4">
              <Button onClick={handleReset} variant="outline">
                  <RefreshCw className="mr-2 h-4 w-4" />
                  Analyze Another Image
              </Button>
          </div>
        </div>
      );
    }
    
    return <ImageUpload onUpload={handleImageUpload} isAnalyzing={isAnalyzing} />;
  }

  return (
    <div className="flex flex-col min-h-screen bg-background font-body">
      <header className="sticky top-0 z-20 flex items-center justify-center w-full h-16 border-b border-border/20 bg-background/80 backdrop-blur-sm">
        <div className="flex items-center gap-2">
          <Bot className="h-6 w-6 text-primary" />
          <h1 className="text-xl font-bold tracking-tight text-foreground">
            AI Image Detective
          </h1>
        </div>
      </header>

      <main className="flex flex-1 w-full flex-col items-center justify-center p-4 sm:p-8 relative overflow-hidden">
        <div className="absolute inset-0 -z-10 h-full w-full bg-background bg-[linear-gradient(to_right,#8080800a_1px,transparent_1px),linear-gradient(to_bottom,#8080800a_1px,transparent_1px)] bg-[size:14px_24px]"></div>
        <div className="absolute left-0 right-0 top-[-10%] h-[1000px] w-[1000px] rounded-full bg-[radial-gradient(circle_400px_at_50%_300px,#fbfbfb36,#000)]"></div>
        
        <div className="z-10 w-full max-w-xl mx-auto animate-fade-in-up" style={{ animationDuration: '0.8s' }}>
          {!analysisResult && (
            <section className="text-center mb-12">
              <h2 className="font-headline text-5xl sm:text-6xl md:text-7xl font-bold tracking-tight text-foreground bg-gradient-to-b from-neutral-50 to-neutral-400 bg-clip-text text-transparent">
                Uncover the Truth
              </h2>
              <p className="mt-6 text-lg sm:text-xl text-foreground/80 max-w-2xl mx-auto">
                Instantly analyze if an image was generated by AI.
              </p>
            </section>
          )}

          <section>
            {renderContent()}
            {error && <p className="text-destructive text-center mt-4">{error}</p>}
          </section>
        </div>

        <footer className="absolute bottom-6 text-sm text-foreground/60 z-10 animate-fade-in-up" style={{ animationDuration: '0.8s', animationDelay: '0.2s' }}>
          Built by an AI Assistant
        </footer>
      </main>
    </div>
  );
}
