'use client';

import { useState } from 'react';
import { analyzeUploadedImage, AnalyzeUploadedImageOutput } from '@/ai/flows/analyze-uploaded-image';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Progress } from '@/components/ui/progress';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { Upload, CheckCircle, XCircle, Bot } from 'lucide-react';

export default function Home() {
  const [file, setFile] = useState<File | null>(null);
  const [analysis, setAnalysis] = useState<AnalyzeUploadedImageOutput | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [previewUrl, setPreviewUrl] = useState<string | null>(null);

  const handleFileChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    const selectedFile = event.target.files?.[0];
    if (selectedFile) {
      setFile(selectedFile);
      setAnalysis(null);
      setError(null);
      const reader = new FileReader();
      reader.onloadend = () => {
        setPreviewUrl(reader.result as string);
      };
      reader.readAsDataURL(selectedFile);
    }
  };

  const handleAnalysis = async () => {
    if (!file) {
      setError('Please select a file first.');
      return;
    }
    setIsLoading(true);
    setError(null);
    setAnalysis(null);

    const reader = new FileReader();
    reader.readAsDataURL(file);
    reader.onload = async () => {
      try {
        const result = await analyzeUploadedImage({ photoDataUri: reader.result as string });
        setAnalysis(result);
      } catch (err: any) {
        setError(err.message || 'An error occurred during analysis.');
      } finally {
        setIsLoading(false);
      }
    };
    reader.onerror = () => {
      setError('Failed to read file.');
      setIsLoading(false);
    };
  };

  return (
    <main className="flex min-h-screen w-full items-center justify-center p-4 sm:p-8 relative overflow-hidden font-body bg-background">
      <div 
        className="absolute inset-0 z-0"
        style={{
          backgroundImage: 'radial-gradient(circle at 15% 25%, hsl(var(--primary) / 0.1), transparent 35%), radial-gradient(circle at 85% 75%, hsl(var(--accent) / 0.12), transparent 40%)'
        }} 
      />
      <div 
        className="absolute inset-0 z-0"
        style={{
          backgroundImage: 'linear-gradient(hsl(var(--primary)/0.03) 1px, transparent 1px), linear-gradient(90deg, hsl(var(--primary)/0.03) 1px, transparent 1px)',
          backgroundSize: '2.5rem 2.5rem'
        }} 
      />
      
      <div className="z-10 grid grid-cols-1 md:grid-cols-2 gap-8 md:gap-12 items-center w-full max-w-6xl mx-auto animate-fade-in-up" style={{ animationDuration: '0.8s' }}>
        <div className="text-center md:text-left">
          <h1 className="font-headline text-4xl sm:text-5xl md:text-6xl font-bold tracking-tight text-foreground">
            AI Image Detective
          </h1>
          <p className="mt-4 text-lg sm:text-xl text-foreground/80 max-w-2xl">
            Upload an image to instantly analyze if it was generated by AI.
          </p>
        </div>

        <Card className="w-full bg-card/80 backdrop-blur-sm border-border/50">
          <CardHeader>
            <CardTitle className="flex items-center justify-center gap-2">
              <Bot className="h-6 w-6" />
              Analyze Image
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-6">
            <div className="space-y-2">
              <div className="flex items-center justify-center w-full">
                <label htmlFor="file-upload" className="flex flex-col items-center justify-center w-full h-64 border-2 border-border border-dashed rounded-lg cursor-pointer bg-card hover:bg-secondary/50 transition-colors">
                  {previewUrl ? (
                    <img src={previewUrl} alt="Image preview" className="object-contain h-full w-full rounded-lg" />
                  ) : (
                    <div className="flex flex-col items-center justify-center pt-5 pb-6">
                      <Upload className="w-10 h-10 mb-3 text-muted-foreground" />
                      <p className="mb-2 text-sm text-muted-foreground"><span className="font-semibold">Click to upload</span> or drag and drop</p>
                      <p className="text-xs text-muted-foreground">PNG, JPG, or WEBP</p>
                    </div>
                  )}
                  <Input id="file-upload" type="file" className="hidden" onChange={handleFileChange} accept="image/png, image/jpeg, image/webp" />
                </label>
              </div>
            </div>

            <Button onClick={handleAnalysis} disabled={!file || isLoading} className="w-full text-lg py-6">
              {isLoading ? 'Analyzing...' : 'Analyze Image'}
            </Button>

            {isLoading && <Progress value={(analysis?.confidence ?? 0) * 100} className="w-full" />}
            
            {error && (
              <Alert variant="destructive">
                <XCircle className="h-4 w-4" />
                <AlertTitle>Error</AlertTitle>
                <AlertDescription>{error}</AlertDescription>
              </Alert>
            )}

            {analysis && (
              <Alert variant={analysis.isAiGenerated ? 'destructive' : 'default'} className="text-left">
                {analysis.isAiGenerated ? <XCircle className="h-4 w-4" /> : <CheckCircle className="h-4 w-4" />}
                <AlertTitle>{analysis.isAiGenerated ? 'AI Generated Image Detected' : 'Likely Human-Generated'}</AlertTitle>
                <AlertDescription>
                  Our analysis indicates this image is {analysis.isAiGenerated ? 'likely' : 'unlikely'} to be AI-generated with a confidence of {Math.round(analysis.confidence * 100)}%.
                </AlertDescription>
              </Alert>
            )}
          </CardContent>
        </Card>
      </div>

      <footer className="absolute bottom-4 text-sm text-foreground/60 z-10 animate-fade-in-up" style={{ animationDuration: '0.8s', animationDelay: '0.2s' }}>
        Developed by Diljith A K
      </footer>
    </main>
  );
}
