'use client';

import { Card } from '@/components/ui/card';
import { Bot } from 'lucide-react';

declare global {
  namespace JSX {
    interface IntrinsicElements {
      'gradio-app': React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement> & {
        src?: string;
      }, HTMLElement>;
    }
  }
}

export default function Home() {
  return (
    <main className="flex min-h-screen w-full flex-col items-center justify-center p-4 sm:p-8 relative overflow-hidden font-body bg-background">
      <div className="absolute inset-0 -z-10 h-full w-full bg-background bg-[linear-gradient(to_right,#8080800a_1px,transparent_1px),linear-gradient(to_bottom,#8080800a_1px,transparent_1px)] bg-[size:14px_24px]"></div>
      <div className="absolute left-0 right-0 top-[-10%] h-[1000px] w-[1000px] rounded-full bg-[radial-gradient(circle_400px_at_50%_300px,#fbfbfb36,#000)]"></div>
      
      <div className="z-10 w-full max-w-4xl mx-auto animate-fade-in-up" style={{ animationDuration: '0.8s' }}>
        <div className="text-center mb-12">
          <h1 className="font-headline text-5xl sm:text-6xl md:text-7xl font-bold tracking-tight text-foreground bg-gradient-to-b from-neutral-50 to-neutral-400 bg-clip-text text-transparent">
            AI Image Detective
          </h1>
          <p className="mt-6 text-lg sm:text-xl text-foreground/80 max-w-2xl mx-auto">
            Uncover the truth. Instantly analyze if an image was generated by AI.
          </p>
        </div>

        <Card className="w-full bg-card/80 backdrop-blur-sm border-border/20 shadow-xl shadow-black/10 overflow-hidden rounded-2xl">
          <div className="gradio-container">
            <gradio-app src="https://thrimurthi2025-ai-or-not.hf.space"></gradio-app>
          </div>
        </Card>
      </div>

      <footer className="absolute bottom-6 text-sm text-foreground/60 z-10 animate-fade-in-up" style={{ animationDuration: '0.8s', animationDelay: '0.2s' }}>
        Built by an AI Assistant
      </footer>
    </main>
  );
}
