import Link from 'next/link';
import { cn } from '@/lib/utils';
import { Bot } from 'lucide-react';

export function TextDetectorCardLink() {
  return (
    <Link href="/text-detector" className={cn("text-detector-card-link")}>
      <span className="border-light top"></span>
      <span className="border-light right"></span>
      <span className="border-light bottom"></span>
      <span className="border-light left"></span>
      <div className="card-content">
        <span className="card-icon"><Bot /></span>
        <div className="card-text">
          <h3 className="card-title">AI Content Detector</h3>
          <p className="card-desc">Analyze text to detect if it was generated by an AI.</p>
        </div>
      </div>
    </Link>
  )
}
